// <auto-generated />
namespace StoredProcedure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_bookchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_bookchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "202007161140587_mig_bookchanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
